[project]
name = "Media-downloader"
version = "0.1.0"
description = "downaloder all kind of media form all platform"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.14",
    "pydantic>=2.11.7",
    "uvicorn>=0.35.0",
    "yt-dlp>=2025.6.25",
]
